// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEE61_L9eeljM1IG8i9HMTU1AfKqCl-Xg',
    appId: '1:303675115793:web:1133a9d6be0ee0013de4b0',
    messagingSenderId: '303675115793',
    projectId: 'flutter-f0659',
    authDomain: 'flutter-f0659.firebaseapp.com',
    storageBucket: 'flutter-f0659.appspot.com',
    measurementId: 'G-591ZYZ7TK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw2Yy6o9kuliMLrnEOcecv6vgYaBHs0HY',
    appId: '1:303675115793:android:7032fc61484c4ef33de4b0',
    messagingSenderId: '303675115793',
    projectId: 'flutter-f0659',
    storageBucket: 'flutter-f0659.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClavhZB5Jmf8duXKlwsY8KFe75T_qH7lk',
    appId: '1:303675115793:ios:e314840b540f53393de4b0',
    messagingSenderId: '303675115793',
    projectId: 'flutter-f0659',
    storageBucket: 'flutter-f0659.appspot.com',
    iosClientId: '303675115793-7b2ts5n80v76pclo5tefa4t4rp32gvas.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClavhZB5Jmf8duXKlwsY8KFe75T_qH7lk',
    appId: '1:303675115793:ios:e314840b540f53393de4b0',
    messagingSenderId: '303675115793',
    projectId: 'flutter-f0659',
    storageBucket: 'flutter-f0659.appspot.com',
    iosClientId: '303675115793-7b2ts5n80v76pclo5tefa4t4rp32gvas.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
