name: test_native_plusplus
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^2.2.0
  flutter_gallery_assets: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - packages/flutter_gallery_assets/crane/destinations/fly_0.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_1.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_2.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_3.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_4.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_5.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_6.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_7.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_8.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_9.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_10.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_11.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_12.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_13.jpg

