name: home_screen_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  fluttertoast: ^8.1.1
  flutter_svg: ^1.1.6
  dio: ^4.0.6
  connectivity: ^3.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  path_provider: ^2.0.11
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.2
  flutter_cache_manager: ^3.3.0
  flutter_inapp_purchase: ^5.3.1
  video_player: ^2.4.7
  chewie: ^1.3.5
  loop_page_view: ^1.2.0
  share_plus: ^6.3.0
  in_app_review: ^2.0.4
  store_redirect: ^2.0.1
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/app/res/image/

  fonts:
    - family: Roboto-Thin
      fonts:
        - asset: lib/app/res/font/Roboto-Thin.ttf
    - family: Roboto-Regular
      fonts:
        - asset: lib/app/res/font/Roboto-Regular.ttf
    - family: Roboto-Medium
      fonts:
        - asset: lib/app/res/font/Roboto-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: lib/app/res/font/Roboto-Bold.ttf
    - family: Roboto-Italic
      fonts:
        - asset: lib/app/res/font/Roboto-Italic.ttf
    - family: Roboto-Light
      fonts:
        - asset: lib/app/res/font/Roboto-Light.ttf

flutter_native_splash:
  color: "#000000"
  image: lib/app/res/image/ic_logo.svg